### ISSUE TITLE
Unable to use this module in ES6 projects

### ISSUE THREAD

**Issue by gmarkv10** [mmckelvy/walk-object#5]
This synchronous part of this module works as advertised and saved me time writing my own object traversal routine. However, in order to get it to run in my ES6 project (running node v6.10.1 npm v3.10.10) I had to comment out the function exported in walk-object-async.js since the async keyword (and related keywords) are not available below ES7. 

It would be nice to be able to keep this in my package.json so you can get credit for it, but it will cause SyntaxError's after every install. Can you make a separate tag, repo, or otherwise make the async part of the module optional for use in older projects?

**Comment by mmckelvy** [comment]
Hi @gmarkv10 .  The easiest and cleanest solution is probably to break out the synchronous version as a separate module, which I can do shortly.

**Comment by mmckelvy** [comment]
@gmarkv10 Sync only package up [here](https://www.npmjs.com/package/walk-object-sync).

**Comment by gmarkv10** [comment]
You're a champion, mate.
